### ISSUE TITLE
Quick Feedback

### ISSUE THREAD

**Issue by aXlireza** [MaryamGolparvar/manage-landing-page#1]
Hey, wonderful job, the responsiveness works great just that the menu doesn't pull on mobile view and that the part that I've got an screenshot attached, is a bit too close to the edges and the right side of the boxes are completely attached to the edge, not sure if this was intentional but it doesn't feel right.
Keep it up.
![image](https://github.com/MaryamGolparvar/manage-landing-page/assets/94176144/8b2b6bbf-46a7-4f18-922f-1258f7fe8fb3)

**Comment by MaryamGolparvar** [comment]
Thanks, dear Alireza for informing me
I'll definitely fix it as soon as possible.
